"""Generate connected mock APM tables for topology graph testing."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable

TABLE_FIELDS: dict[str, list[str]] = {
    "apm_cluster": ["id", "name", "environment", "region", "owner_team"],
    "apm_subclusters": ["id", "name", "apm_cluster", "role", "zone"],
    "apm_applications": [
        "id",
        "name",
        "apm_cluster",
        "production_domain_manager",
        "application_manager",
        "domain_manager",
        "production_manager",
        "apm_spoc",
        "criticality",
        "business_owner",
        "runtime_tier",
    ],
    "apm_contacts": ["id", "name", "refog"],
    "apm_application_daps": [
        "id",
        "apm_application",
        "dap_id",
        "dap_name",
        "direction",
        "protocol",
    ],
    "apm_technologies": ["id", "name", "category", "vendor", "version", "lifecycle"],
    "apm_obso": [
        "id",
        "application_id",
        "technology_id",
        "host",
        "criticality",
        "env",
        "location_country",
        "obsolescence_status",
        "risk_level",
        "detected_at",
        "evidence",
    ],
}


def mock_tables() -> dict[str, list[dict[str, str]]]:
    return {
        "apm_cluster": [
            {
                "id": "cl_eu_prod",
                "name": "EU Production",
                "environment": "prod",
                "region": "eu-west",
                "owner_team": "platform-eu",
            },
            {
                "id": "cl_us_prod",
                "name": "US Production",
                "environment": "prod",
                "region": "us-east",
                "owner_team": "platform-us",
            },
            {
                "id": "cl_data_platform",
                "name": "Data Platform",
                "environment": "prod",
                "region": "global",
                "owner_team": "data-platform",
            },
        ],
        "apm_subclusters": [
            {
                "id": "sub_eu_core",
                "name": "EU Core Services",
                "apm_cluster": "cl_eu_prod",
                "role": "services",
                "zone": "eu-west-1a",
            },
            {
                "id": "sub_eu_edge",
                "name": "EU Edge",
                "apm_cluster": "cl_eu_prod",
                "role": "ingress",
                "zone": "eu-west-1b",
            },
            {
                "id": "sub_us_core",
                "name": "US Core Services",
                "apm_cluster": "cl_us_prod",
                "role": "services",
                "zone": "us-east-1a",
            },
            {
                "id": "sub_us_batch",
                "name": "US Batch",
                "apm_cluster": "cl_us_prod",
                "role": "batch",
                "zone": "us-east-1c",
            },
            {
                "id": "sub_data_streaming",
                "name": "Streaming Platform",
                "apm_cluster": "cl_data_platform",
                "role": "streaming",
                "zone": "global-a",
            },
            {
                "id": "sub_data_warehouse",
                "name": "Warehouse Platform",
                "apm_cluster": "cl_data_platform",
                "role": "warehouse",
                "zone": "global-b",
            },
        ],
        "apm_applications": [
            {
                "id": "app_payments",
                "name": "Payments API",
                "apm_cluster": "cl_eu_prod",
                "production_domain_manager": "contact_alice",
                "application_manager": "contact_boris",
                "domain_manager": "contact_chloe",
                "production_manager": "contact_daniel",
                "apm_spoc": "contact_elena",
                "criticality": "tier_1",
                "business_owner": "payments",
                "runtime_tier": "api",
            },
            {
                "id": "app_auth",
                "name": "Identity Service",
                "apm_cluster": "cl_eu_prod",
                "production_domain_manager": "contact_alice",
                "application_manager": "contact_boris",
                "domain_manager": "contact_chloe",
                "production_manager": "contact_daniel",
                "apm_spoc": "contact_boris",
                "criticality": "tier_1",
                "business_owner": "platform",
                "runtime_tier": "service",
            },
            {
                "id": "app_search",
                "name": "Search Gateway",
                "apm_cluster": "cl_eu_prod",
                "production_domain_manager": "contact_alice",
                "application_manager": "contact_farah",
                "domain_manager": "contact_chloe",
                "production_manager": "contact_daniel",
                "apm_spoc": "contact_elena",
                "criticality": "tier_2",
                "business_owner": "commerce",
                "runtime_tier": "edge",
            },
            {
                "id": "app_billing",
                "name": "Billing Worker",
                "apm_cluster": "cl_us_prod",
                "production_domain_manager": "contact_farah",
                "application_manager": "contact_boris",
                "domain_manager": "contact_chloe",
                "production_manager": "contact_daniel",
                "apm_spoc": "contact_elena",
                "criticality": "tier_1",
                "business_owner": "finance",
                "runtime_tier": "worker",
            },
            {
                "id": "app_inventory",
                "name": "Inventory Service",
                "apm_cluster": "cl_us_prod",
                "production_domain_manager": "contact_farah",
                "application_manager": "contact_boris",
                "domain_manager": "contact_chloe",
                "production_manager": "contact_alice",
                "apm_spoc": "contact_elena",
                "criticality": "tier_2",
                "business_owner": "supply-chain",
                "runtime_tier": "service",
            },
            {
                "id": "app_events",
                "name": "Event Collector",
                "apm_cluster": "cl_data_platform",
                "production_domain_manager": "contact_farah",
                "application_manager": "contact_chloe",
                "domain_manager": "contact_chloe",
                "production_manager": "contact_daniel",
                "apm_spoc": "contact_elena",
                "criticality": "tier_1",
                "business_owner": "data-platform",
                "runtime_tier": "streaming",
            },
            {
                "id": "app_warehouse",
                "name": "Warehouse Loader",
                "apm_cluster": "cl_data_platform",
                "production_domain_manager": "contact_farah",
                "application_manager": "contact_chloe",
                "domain_manager": "contact_chloe",
                "production_manager": "contact_daniel",
                "apm_spoc": "contact_elena",
                "criticality": "tier_2",
                "business_owner": "analytics",
                "runtime_tier": "batch",
            },
        ],
        "apm_contacts": [
            {"id": "contact_alice", "name": "Alice Laurent", "refog": "u1001"},
            {"id": "contact_boris", "name": "Boris Martin", "refog": "u1002"},
            {"id": "contact_chloe", "name": "Chloe Dubois", "refog": "u1003"},
            {"id": "contact_daniel", "name": "Daniel Moreau", "refog": "u1004"},
            {"id": "contact_elena", "name": "Elena Rossi", "refog": "u1005"},
            {"id": "contact_farah", "name": "Farah Haddad", "refog": "u1006"},
        ],
        "apm_application_daps": [
            {
                "id": "adap_001",
                "apm_application": "app_payments",
                "dap_id": "dap_payment_events",
                "dap_name": "Payment Events",
                "direction": "producer",
                "protocol": "kafka",
            },
            {
                "id": "adap_002",
                "apm_application": "app_payments",
                "dap_id": "dap_auth_context",
                "dap_name": "Auth Context",
                "direction": "consumer",
                "protocol": "https",
            },
            {
                "id": "adap_003",
                "apm_application": "app_auth",
                "dap_id": "dap_auth_context",
                "dap_name": "Auth Context",
                "direction": "producer",
                "protocol": "https",
            },
            {
                "id": "adap_004",
                "apm_application": "app_search",
                "dap_id": "dap_product_index",
                "dap_name": "Product Index",
                "direction": "consumer",
                "protocol": "https",
            },
            {
                "id": "adap_005",
                "apm_application": "app_billing",
                "dap_id": "dap_payment_events",
                "dap_name": "Payment Events",
                "direction": "consumer",
                "protocol": "kafka",
            },
            {
                "id": "adap_006",
                "apm_application": "app_inventory",
                "dap_id": "dap_inventory_snapshot",
                "dap_name": "Inventory Snapshot",
                "direction": "producer",
                "protocol": "s3",
            },
            {
                "id": "adap_007",
                "apm_application": "app_events",
                "dap_id": "dap_payment_events",
                "dap_name": "Payment Events",
                "direction": "consumer",
                "protocol": "kafka",
            },
            {
                "id": "adap_008",
                "apm_application": "app_events",
                "dap_id": "dap_raw_clickstream",
                "dap_name": "Raw Clickstream",
                "direction": "producer",
                "protocol": "kafka",
            },
            {
                "id": "adap_009",
                "apm_application": "app_warehouse",
                "dap_id": "dap_inventory_snapshot",
                "dap_name": "Inventory Snapshot",
                "direction": "consumer",
                "protocol": "s3",
            },
            {
                "id": "adap_010",
                "apm_application": "app_warehouse",
                "dap_id": "dap_curated_metrics",
                "dap_name": "Curated Metrics",
                "direction": "producer",
                "protocol": "snowflake",
            },
        ],
        "apm_technologies": [
            {
                "id": "tech_java8",
                "name": "Java",
                "category": "runtime",
                "vendor": "Oracle",
                "version": "8",
                "lifecycle": "obsolete",
            },
            {
                "id": "tech_java17",
                "name": "Java",
                "category": "runtime",
                "vendor": "Eclipse Adoptium",
                "version": "17",
                "lifecycle": "supported",
            },
            {
                "id": "tech_node16",
                "name": "Node.js",
                "category": "runtime",
                "vendor": "OpenJS",
                "version": "16",
                "lifecycle": "obsolete",
            },
            {
                "id": "tech_python39",
                "name": "Python",
                "category": "runtime",
                "vendor": "Python Software Foundation",
                "version": "3.9",
                "lifecycle": "aging",
            },
            {
                "id": "tech_postgres12",
                "name": "PostgreSQL",
                "category": "database",
                "vendor": "PostgreSQL",
                "version": "12",
                "lifecycle": "obsolete",
            },
            {
                "id": "tech_kafka28",
                "name": "Kafka",
                "category": "messaging",
                "vendor": "Apache",
                "version": "2.8",
                "lifecycle": "aging",
            },
            {
                "id": "tech_nginx117",
                "name": "Nginx",
                "category": "proxy",
                "vendor": "F5",
                "version": "1.17",
                "lifecycle": "obsolete",
            },
            {
                "id": "tech_oracle11g",
                "name": "Oracle Database",
                "category": "database",
                "vendor": "Oracle",
                "version": "11g",
                "lifecycle": "obsolete",
            },
        ],
        "apm_obso": [
            {
                "id": "obso_001",
                "application_id": "app_payments",
                "technology_id": "tech_java8",
                "host": "pay-api-01.eu.prod",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "DE",
                "obsolescence_status": "obsolete",
                "risk_level": "high",
                "detected_at": "2026-05-18",
                "evidence": "runtime scan",
            },
            {
                "id": "obso_002",
                "application_id": "app_payments",
                "technology_id": "tech_postgres12",
                "host": "pay-db-01.eu.prod",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "DE",
                "obsolescence_status": "obsolete",
                "risk_level": "critical",
                "detected_at": "2026-05-18",
                "evidence": "cmdb",
            },
            {
                "id": "obso_003",
                "application_id": "app_payments",
                "technology_id": "tech_kafka28",
                "host": "shared-kafka-01.global",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "IE",
                "obsolescence_status": "aging",
                "risk_level": "medium",
                "detected_at": "2026-05-20",
                "evidence": "runtime scan",
            },
            {
                "id": "obso_004",
                "application_id": "app_auth",
                "technology_id": "tech_java17",
                "host": "auth-api-01.eu.prod",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "DE",
                "obsolescence_status": "supported",
                "risk_level": "low",
                "detected_at": "2026-05-21",
                "evidence": "runtime scan",
            },
            {
                "id": "obso_005",
                "application_id": "app_auth",
                "technology_id": "tech_postgres12",
                "host": "auth-db-01.eu.prod",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "DE",
                "obsolescence_status": "obsolete",
                "risk_level": "high",
                "detected_at": "2026-05-21",
                "evidence": "cmdb",
            },
            {
                "id": "obso_006",
                "application_id": "app_search",
                "technology_id": "tech_node16",
                "host": "edge-01.eu.prod",
                "criticality": "tier_2",
                "env": "prod",
                "location_country": "FR",
                "obsolescence_status": "obsolete",
                "risk_level": "medium",
                "detected_at": "2026-05-22",
                "evidence": "container image",
            },
            {
                "id": "obso_007",
                "application_id": "app_search",
                "technology_id": "tech_nginx117",
                "host": "edge-01.eu.prod",
                "criticality": "tier_2",
                "env": "prod",
                "location_country": "FR",
                "obsolescence_status": "obsolete",
                "risk_level": "medium",
                "detected_at": "2026-05-22",
                "evidence": "package scan",
            },
            {
                "id": "obso_008",
                "application_id": "app_billing",
                "technology_id": "tech_java8",
                "host": "billing-worker-01.us.prod",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "US",
                "obsolescence_status": "obsolete",
                "risk_level": "high",
                "detected_at": "2026-05-23",
                "evidence": "runtime scan",
            },
            {
                "id": "obso_009",
                "application_id": "app_billing",
                "technology_id": "tech_oracle11g",
                "host": "billing-db-01.us.prod",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "US",
                "obsolescence_status": "obsolete",
                "risk_level": "critical",
                "detected_at": "2026-05-23",
                "evidence": "cmdb",
            },
            {
                "id": "obso_010",
                "application_id": "app_inventory",
                "technology_id": "tech_python39",
                "host": "inventory-api-01.us.prod",
                "criticality": "tier_2",
                "env": "prod",
                "location_country": "US",
                "obsolescence_status": "aging",
                "risk_level": "medium",
                "detected_at": "2026-05-24",
                "evidence": "runtime scan",
            },
            {
                "id": "obso_011",
                "application_id": "app_inventory",
                "technology_id": "tech_postgres12",
                "host": "inventory-db-01.us.prod",
                "criticality": "tier_2",
                "env": "prod",
                "location_country": "US",
                "obsolescence_status": "obsolete",
                "risk_level": "high",
                "detected_at": "2026-05-24",
                "evidence": "cmdb",
            },
            {
                "id": "obso_012",
                "application_id": "app_events",
                "technology_id": "tech_kafka28",
                "host": "shared-kafka-01.global",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "IE",
                "obsolescence_status": "aging",
                "risk_level": "medium",
                "detected_at": "2026-05-25",
                "evidence": "runtime scan",
            },
            {
                "id": "obso_013",
                "application_id": "app_events",
                "technology_id": "tech_python39",
                "host": "event-collector-01.global",
                "criticality": "tier_1",
                "env": "prod",
                "location_country": "IE",
                "obsolescence_status": "aging",
                "risk_level": "medium",
                "detected_at": "2026-05-25",
                "evidence": "container image",
            },
            {
                "id": "obso_014",
                "application_id": "app_warehouse",
                "technology_id": "tech_python39",
                "host": "warehouse-loader-01.global",
                "criticality": "tier_2",
                "env": "prod",
                "location_country": "IE",
                "obsolescence_status": "aging",
                "risk_level": "medium",
                "detected_at": "2026-05-26",
                "evidence": "runtime scan",
            },
        ],
    }


def write_mock_data(output_dir: Path | str) -> None:
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)
    tables = mock_tables()

    for table_name, rows in tables.items():
        _write_csv(path / f"{table_name}.csv", TABLE_FIELDS[table_name], rows)


def _write_csv(path: Path, fields: list[str], rows: Iterable[dict[str, str]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


if __name__ == "__main__":
    write_mock_data(Path("data/mock"))
