#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict, deque
from pathlib import Path
from typing import Any


EXPECTED_NODE_LABELS = {
    "Application",
    "ApplicationDap",
    "Cluster",
    "Contact",
    "Criticality",
    "Dap",
    "Environment",
    "Host",
    "LocationCountry",
    "ObsolescenceRecord",
    "Subcluster",
    "Technology",
}

EXPECTED_RELATIONSHIPS = {
    "DEPLOYED_ON": {("Application", "Host")},
    "EXPOSES_DAP": {("Application", "Dap")},
    "HAS_APPLICATION": {("Cluster", "Application")},
    "HAS_APPLICATION_MANAGER": {("Application", "Contact")},
    "HAS_APM_SPOC": {("Application", "Contact")},
    "HAS_CRITICALITY": {("ObsolescenceRecord", "Criticality")},
    "HAS_DAP_BINDING": {("Application", "ApplicationDap")},
    "HAS_DOMAIN_MANAGER": {("Application", "Contact")},
    "HAS_OBSOLESCENCE_RECORD": {("Application", "ObsolescenceRecord")},
    "HAS_PRODUCTION_DOMAIN_MANAGER": {("Application", "Contact")},
    "HAS_PRODUCTION_MANAGER": {("Application", "Contact")},
    "HAS_SUBCLUSTER": {("Cluster", "Subcluster")},
    "HAS_TECHNOLOGY": {("Host", "Technology")},
    "IN_ENVIRONMENT": {("ObsolescenceRecord", "Environment")},
    "LOCATED_IN_COUNTRY": {("ObsolescenceRecord", "LocationCountry")},
    "ON_HOST": {("ObsolescenceRecord", "Host")},
    "REFERENCES_TECHNOLOGY": {("ObsolescenceRecord", "Technology")},
    "RELATED_TO": {("Application", "Application")},
    "TARGETS_DAP": {("ApplicationDap", "Dap")},
    "USES_TECHNOLOGY": {("Application", "Technology")},
}

COVERAGE_REQUIREMENTS = [
    ("Application", "incoming", {"HAS_APPLICATION"}, "applications attached to a cluster"),
    (
        "Application",
        "outgoing",
        {
            "HAS_APPLICATION_MANAGER",
            "HAS_APM_SPOC",
            "HAS_DOMAIN_MANAGER",
            "HAS_PRODUCTION_DOMAIN_MANAGER",
            "HAS_PRODUCTION_MANAGER",
        },
        "applications attached to at least one contact role",
    ),
    ("Subcluster", "incoming", {"HAS_SUBCLUSTER"}, "subclusters attached to a cluster"),
    (
        "Contact",
        "incoming",
        {
            "HAS_APPLICATION_MANAGER",
            "HAS_APM_SPOC",
            "HAS_DOMAIN_MANAGER",
            "HAS_PRODUCTION_DOMAIN_MANAGER",
            "HAS_PRODUCTION_MANAGER",
        },
        "contacts referenced by an application role",
    ),
    ("ApplicationDap", "incoming", {"HAS_DAP_BINDING"}, "DAP binding rows attached to an application"),
    ("ApplicationDap", "outgoing", {"TARGETS_DAP"}, "DAP binding rows point to a DAP"),
    ("ObsolescenceRecord", "incoming", {"HAS_OBSOLESCENCE_RECORD"}, "obsolescence rows attached to an application"),
    ("ObsolescenceRecord", "outgoing", {"ON_HOST"}, "obsolescence rows point to a host"),
    ("ObsolescenceRecord", "outgoing", {"REFERENCES_TECHNOLOGY"}, "obsolescence rows point to a technology"),
    ("Criticality", "incoming", {"HAS_CRITICALITY"}, "criticality values are referenced by obsolescence rows"),
    ("Environment", "incoming", {"IN_ENVIRONMENT"}, "environment values are referenced by obsolescence rows"),
    ("LocationCountry", "incoming", {"LOCATED_IN_COUNTRY"}, "country values are referenced by obsolescence rows"),
    ("Dap", "incoming", {"EXPOSES_DAP", "TARGETS_DAP"}, "DAPs referenced by an application or binding row"),
    ("Host", "incoming", {"DEPLOYED_ON", "ON_HOST"}, "hosts referenced by an application or obsolescence row"),
    ("Technology", "incoming", {"REFERENCES_TECHNOLOGY", "USES_TECHNOLOGY", "HAS_TECHNOLOGY"}, "technologies referenced by topology data"),
]

OPTIONAL_COVERAGE_REQUIREMENTS = [
    ("ObsolescenceRecord", "outgoing", {"HAS_CRITICALITY"}, "obsolescence rows point to a criticality"),
    ("ObsolescenceRecord", "outgoing", {"IN_ENVIRONMENT"}, "obsolescence rows point to an environment"),
    ("ObsolescenceRecord", "outgoing", {"LOCATED_IN_COUNTRY"}, "obsolescence rows point to a country"),
]

REQUIRED_PROPERTIES = {
    "Application": {"id"},
    "ApplicationDap": {"id"},
    "Cluster": {"id"},
    "Contact": {"id"},
    "Criticality": {"id"},
    "Dap": {"id"},
    "Environment": {"id"},
    "Host": {"id"},
    "LocationCountry": {"id"},
    "ObsolescenceRecord": {"id"},
    "Subcluster": {"id"},
    "Technology": {"id"},
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate topology graph quality from exported JSON.")
    parser.add_argument("--graph-json", default="build/topology_graph.json", help="Graph JSON generated by export_graph.py.")
    parser.add_argument("--out-json", default=None, help="Optional machine-readable metrics output.")
    parser.add_argument("--top", type=int, default=10, help="Number of examples to show for each issue/hub list.")
    args = parser.parse_args()

    graph_path = Path(args.graph_json)
    graph = json.loads(graph_path.read_text(encoding="utf-8"))
    report = evaluate_graph(graph, top=args.top)
    print_report(report, graph_path)
    if args.out_json:
        output_path = Path(args.out_json)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
        print(f"\nWrote JSON report to {output_path}")


def evaluate_graph(graph: dict[str, Any], *, top: int = 10) -> dict[str, Any]:
    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])
    nodes_by_key = {node["key"]: node for node in nodes}
    label_by_key = {node["key"]: node.get("label", "") for node in nodes}

    incoming: dict[str, list[dict[str, Any]]] = defaultdict(list)
    outgoing: dict[str, list[dict[str, Any]]] = defaultdict(list)
    undirected: dict[str, set[str]] = defaultdict(set)
    broken_edges = []
    schema_violations = []
    duplicate_edge_counts: Counter[tuple[str, str, str]] = Counter()

    for edge in edges:
        edge_key = (edge.get("start_key", ""), edge.get("type", ""), edge.get("end_key", ""))
        duplicate_edge_counts[edge_key] += 1
        start_key = edge.get("start_key", "")
        end_key = edge.get("end_key", "")
        edge_type = edge.get("type", "")
        if start_key not in nodes_by_key or end_key not in nodes_by_key:
            broken_edges.append(edge)
            continue

        outgoing[start_key].append(edge)
        incoming[end_key].append(edge)
        undirected[start_key].add(end_key)
        undirected[end_key].add(start_key)

        expected_pairs = EXPECTED_RELATIONSHIPS.get(edge_type)
        actual_pair = (label_by_key[start_key], label_by_key[end_key])
        if expected_pairs is None or actual_pair not in expected_pairs:
            schema_violations.append(
                {
                    "edge": edge,
                    "actual": actual_pair,
                    "expected": sorted(expected_pairs) if expected_pairs else [],
                }
            )

    for key in nodes_by_key:
        undirected.setdefault(key, set())

    label_counts = Counter(node.get("label", "") for node in nodes)
    relationship_counts = Counter(edge.get("type", "") for edge in edges)
    components = connected_components(nodes_by_key, undirected)
    isolated_nodes = sorted(key for key, neighbors in undirected.items() if not neighbors)
    reachable_from_clusters = directed_reachable_from(labels={"Cluster"}, nodes=nodes, outgoing=outgoing)
    non_cluster_keys = {node["key"] for node in nodes if node.get("label") != "Cluster"}
    unreachable_from_clusters = sorted(non_cluster_keys - reachable_from_clusters)

    duplicate_edges = [
        {"start_key": start, "type": edge_type, "end_key": end, "count": count}
        for (start, edge_type, end), count in duplicate_edge_counts.items()
        if count > 1
    ]

    coverage = coverage_report(nodes, incoming, outgoing)
    property_completeness = property_report(nodes)
    degree_rows = degree_report(nodes, incoming, outgoing, top=top)
    missing_labels = sorted(EXPECTED_NODE_LABELS - set(label_counts))
    unexpected_labels = sorted(set(label_counts) - EXPECTED_NODE_LABELS)
    unexpected_relationships = sorted(set(relationship_counts) - set(EXPECTED_RELATIONSHIPS))

    issue_counts = {
        "broken_edges": len(broken_edges),
        "schema_violations": len(schema_violations),
        "duplicate_edges": len(duplicate_edges),
        "isolated_nodes": len(isolated_nodes),
        "unreachable_from_clusters": len(unreachable_from_clusters),
        "coverage_missing_nodes": sum(item["missing_count"] for item in coverage if item.get("severity") == "required"),
        "optional_coverage_missing_nodes": sum(
            item["missing_count"] for item in coverage if item.get("severity") == "optional"
        ),
        "property_missing_nodes": sum(item["missing_count"] for item in property_completeness),
        "missing_expected_labels": len(missing_labels),
        "unexpected_labels": len(unexpected_labels),
        "unexpected_relationships": len(unexpected_relationships),
    }

    score = quality_score(
        node_count=len(nodes),
        issue_counts=issue_counts,
        largest_component_size=components[0]["size"] if components else 0,
    )
    status = "PASS" if score >= 90 and not has_critical_issues(issue_counts) else "WARN"
    if issue_counts["broken_edges"] or issue_counts["schema_violations"]:
        status = "FAIL"

    return {
        "status": status,
        "quality_score": score,
        "score_note": "Heuristic score. Use concrete issue counts for decisions.",
        "totals": {
            "nodes": len(nodes),
            "edges": len(edges),
            "edge_to_node_ratio": round(len(edges) / len(nodes), 3) if nodes else 0,
        },
        "node_labels": dict(sorted(label_counts.items())),
        "relationship_types": dict(sorted(relationship_counts.items())),
        "connectivity": {
            "component_count": len(components),
            "largest_component_size": components[0]["size"] if components else 0,
            "largest_component_ratio": round((components[0]["size"] / len(nodes)), 4) if nodes and components else 0,
            "component_samples": components[:top],
            "isolated_node_count": len(isolated_nodes),
            "isolated_node_samples": isolated_nodes[:top],
            "unreachable_from_clusters_count": len(unreachable_from_clusters),
            "unreachable_from_clusters_samples": unreachable_from_clusters[:top],
        },
        "schema": {
            "missing_expected_labels": missing_labels,
            "unexpected_labels": unexpected_labels,
            "unexpected_relationship_types": unexpected_relationships,
            "broken_edge_count": len(broken_edges),
            "broken_edge_samples": broken_edges[:top],
            "schema_violation_count": len(schema_violations),
            "schema_violation_samples": schema_violations[:top],
            "duplicate_edge_count": len(duplicate_edges),
            "duplicate_edge_samples": duplicate_edges[:top],
        },
        "coverage": coverage,
        "property_completeness": property_completeness,
        "degree": degree_rows,
        "builder_warnings": graph.get("warnings", []),
        "recommendations": recommendations(issue_counts, components, len(nodes), graph.get("warnings", [])),
    }


def connected_components(nodes_by_key: dict[str, dict[str, Any]], adjacency: dict[str, set[str]]) -> list[dict[str, Any]]:
    seen: set[str] = set()
    components = []
    for key in sorted(nodes_by_key):
        if key in seen:
            continue
        queue = deque([key])
        seen.add(key)
        members = []
        labels = Counter()
        while queue:
            current = queue.popleft()
            members.append(current)
            labels[nodes_by_key[current].get("label", "")] += 1
            for neighbor in adjacency.get(current, set()):
                if neighbor not in seen:
                    seen.add(neighbor)
                    queue.append(neighbor)
        components.append(
            {
                "size": len(members),
                "labels": dict(sorted(labels.items())),
                "sample_nodes": sorted(members)[:8],
            }
        )
    return sorted(components, key=lambda item: item["size"], reverse=True)


def directed_reachable_from(
    *,
    labels: set[str],
    nodes: list[dict[str, Any]],
    outgoing: dict[str, list[dict[str, Any]]],
) -> set[str]:
    start_keys = [node["key"] for node in nodes if node.get("label") in labels]
    seen = set(start_keys)
    queue = deque(start_keys)
    while queue:
        key = queue.popleft()
        for edge in outgoing.get(key, []):
            end_key = edge.get("end_key", "")
            if end_key and end_key not in seen:
                seen.add(end_key)
                queue.append(end_key)
    return seen


def coverage_report(
    nodes: list[dict[str, Any]],
    incoming: dict[str, list[dict[str, Any]]],
    outgoing: dict[str, list[dict[str, Any]]],
) -> list[dict[str, Any]]:
    rows = []
    requirements = [
        *[(label, direction, edge_types, description, "required") for label, direction, edge_types, description in COVERAGE_REQUIREMENTS],
        *[
            (label, direction, edge_types, description, "optional")
            for label, direction, edge_types, description in OPTIONAL_COVERAGE_REQUIREMENTS
        ],
    ]
    for label, direction, edge_types, description, severity in requirements:
        label_nodes = [node for node in nodes if node.get("label") == label]
        missing = []
        for node in label_nodes:
            edges = incoming[node["key"]] if direction == "incoming" else outgoing[node["key"]]
            if not any(edge.get("type") in edge_types for edge in edges):
                missing.append(node["key"])
        total = len(label_nodes)
        rows.append(
            {
                "label": label,
                "direction": direction,
                "relationship_types": sorted(edge_types),
                "description": description,
                "severity": severity,
                "total": total,
                "ok_count": total - len(missing),
                "missing_count": len(missing),
                "coverage_ratio": round(((total - len(missing)) / total), 4) if total else 1.0,
                "missing_samples": missing[:10],
            }
        )
    return rows


def property_report(nodes: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows = []
    for label, required_properties in sorted(REQUIRED_PROPERTIES.items()):
        label_nodes = [node for node in nodes if node.get("label") == label]
        missing = []
        for node in label_nodes:
            properties = node.get("properties", {})
            if any(not properties.get(prop) for prop in required_properties):
                missing.append(node["key"])
        total = len(label_nodes)
        rows.append(
            {
                "label": label,
                "required_properties": sorted(required_properties),
                "total": total,
                "ok_count": total - len(missing),
                "missing_count": len(missing),
                "coverage_ratio": round(((total - len(missing)) / total), 4) if total else 1.0,
                "missing_samples": missing[:10],
            }
        )
    return rows


def degree_report(
    nodes: list[dict[str, Any]],
    incoming: dict[str, list[dict[str, Any]]],
    outgoing: dict[str, list[dict[str, Any]]],
    *,
    top: int,
) -> dict[str, Any]:
    rows = []
    for node in nodes:
        in_degree = len(incoming[node["key"]])
        out_degree = len(outgoing[node["key"]])
        rows.append(
            {
                "key": node["key"],
                "label": node.get("label", ""),
                "name": node.get("properties", {}).get("name", node.get("identity", "")),
                "in_degree": in_degree,
                "out_degree": out_degree,
                "degree": in_degree + out_degree,
            }
        )
    degrees = [row["degree"] for row in rows]
    return {
        "min": min(degrees) if degrees else 0,
        "max": max(degrees) if degrees else 0,
        "average": round((sum(degrees) / len(degrees)), 3) if degrees else 0,
        "top_hubs": sorted(rows, key=lambda item: (item["degree"], item["key"]), reverse=True)[:top],
    }


def quality_score(
    *,
    node_count: int,
    issue_counts: dict[str, int],
    largest_component_size: int,
) -> int:
    if node_count == 0:
        return 0
    isolated_ratio = issue_counts["isolated_nodes"] / node_count
    unreachable_ratio = issue_counts["unreachable_from_clusters"] / node_count
    largest_component_ratio = largest_component_size / node_count
    penalty = 0
    penalty += min(35, issue_counts["broken_edges"] * 5)
    penalty += min(30, issue_counts["schema_violations"] * 5)
    penalty += min(20, issue_counts["duplicate_edges"] * 2)
    penalty += min(20, int(isolated_ratio * 100))
    penalty += min(15, int(unreachable_ratio * 40))
    penalty += min(15, issue_counts["coverage_missing_nodes"])
    penalty += min(10, issue_counts["missing_expected_labels"] * 2)
    if largest_component_ratio < 0.5:
        penalty += 15
    elif largest_component_ratio < 0.8:
        penalty += 5
    return max(0, 100 - penalty)


def has_critical_issues(issue_counts: dict[str, int]) -> bool:
    return bool(
        issue_counts["missing_expected_labels"]
        or issue_counts["unexpected_relationships"]
        or issue_counts["duplicate_edges"]
    )


def recommendations(
    issue_counts: dict[str, int],
    components: list[dict[str, Any]],
    node_count: int,
    builder_warnings: list[str],
) -> list[str]:
    items = []
    if issue_counts["broken_edges"]:
        items.append("Fix broken edges first: some relationships reference missing node keys.")
    if issue_counts["schema_violations"]:
        items.append("Review relationship endpoint labels; at least one edge does not match the expected graph schema.")
    if issue_counts["coverage_missing_nodes"]:
        items.append("Inspect coverage rows with missing_count > 0; these usually indicate missing foreign keys or filtered-out tables.")
    if issue_counts.get("optional_coverage_missing_nodes"):
        items.append(
            "Optional dimension coverage is incomplete; check whether missing criticality/env/country values are expected in apm_obso."
        )
    if issue_counts["isolated_nodes"]:
        items.append("Review isolated nodes; they preserve data but are not useful for topology traversal yet.")
    if node_count and components and components[0]["size"] / node_count < 0.8:
        items.append("The largest connected component is below 80%; verify whether disconnected environments/clusters are expected.")
    if builder_warnings:
        items.append("Review builder warnings from export_graph.py; they may explain skipped derived edges or missing references.")
    if not items:
        items.append("No major structural issues found. Next evaluate domain quality with real expected paths and sample applications.")
    return items


def print_report(report: dict[str, Any], graph_path: Path) -> None:
    print(f"Graph Quality Report: {graph_path}")
    print(f"Status: {report['status']}  Score: {report['quality_score']}/100")
    print(f"Totals: {report['totals']['nodes']} nodes, {report['totals']['edges']} edges")

    print("\nNode labels")
    for label, count in report["node_labels"].items():
        print(f"- {label}: {count}")

    print("\nRelationship types")
    for relationship, count in report["relationship_types"].items():
        print(f"- {relationship}: {count}")

    connectivity = report["connectivity"]
    print("\nConnectivity")
    print(f"- components: {connectivity['component_count']}")
    print(
        "- largest component: "
        f"{connectivity['largest_component_size']} "
        f"({connectivity['largest_component_ratio']:.1%})"
    )
    print(f"- isolated nodes: {connectivity['isolated_node_count']}")
    print(f"- unreachable from clusters: {connectivity['unreachable_from_clusters_count']}")
    if connectivity["isolated_node_samples"]:
        print(f"- isolated samples: {', '.join(connectivity['isolated_node_samples'])}")
    if connectivity["unreachable_from_clusters_samples"]:
        print(f"- unreachable samples: {', '.join(connectivity['unreachable_from_clusters_samples'])}")

    schema = report["schema"]
    print("\nSchema")
    print(f"- broken edges: {schema['broken_edge_count']}")
    print(f"- schema violations: {schema['schema_violation_count']}")
    print(f"- duplicate edges: {schema['duplicate_edge_count']}")
    if schema["missing_expected_labels"]:
        print(f"- missing expected labels: {', '.join(schema['missing_expected_labels'])}")
    if schema["unexpected_labels"]:
        print(f"- unexpected labels: {', '.join(schema['unexpected_labels'])}")
    if schema["unexpected_relationship_types"]:
        print(f"- unexpected relationship types: {', '.join(schema['unexpected_relationship_types'])}")

    print("\nCoverage")
    for row in report["coverage"]:
        if row["total"] == 0:
            continue
        if row["missing_count"] == 0:
            marker = "OK"
        elif row.get("severity") == "optional":
            marker = "INFO"
        else:
            marker = "WARN"
        print(
            f"- {marker} {row['description']}: "
            f"{row['ok_count']}/{row['total']} "
            f"({row['coverage_ratio']:.1%})"
        )
        if row["missing_samples"]:
            print(f"  samples: {', '.join(row['missing_samples'])}")

    print("\nTop hubs")
    for row in report["degree"]["top_hubs"]:
        print(
            f"- {row['key']} [{row['label']}]: degree={row['degree']} "
            f"in={row['in_degree']} out={row['out_degree']}"
        )

    if report["builder_warnings"]:
        print("\nBuilder warnings")
        for warning in report["builder_warnings"][:10]:
            print(f"- {warning}")
        if len(report["builder_warnings"]) > 10:
            print(f"- ... {len(report['builder_warnings']) - 10} more")

    print("\nRecommendations")
    for item in report["recommendations"]:
        print(f"- {item}")


if __name__ == "__main__":
    main()
