#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Render a self-contained HTML topology graph viewer.")
    parser.add_argument("--graph-json", default="build/topology_graph.json", help="Graph JSON generated by export_graph.py.")
    parser.add_argument("--output", default="build/topology_viewer.html", help="Output HTML file.")
    parser.add_argument("--max-nodes", type=int, default=120, help="Maximum nodes to render in sampled mode.")
    parser.add_argument("--max-edges", type=int, default=180, help="Maximum edges to render in sampled mode.")
    parser.add_argument("--full", action="store_true", help="Render the full graph instead of a representative sample.")
    parser.add_argument("--application-name", "--app-name", default=None, help="Render the neighborhood for applications matching this name.")
    parser.add_argument("--application-id", "--app-id", default=None, help="Render the neighborhood for this application id.")
    parser.add_argument("--focus-depth", type=int, default=2, help="Relationship hops to include around the focused application.")
    parser.add_argument(
        "--exclude-edge-type",
        action="append",
        default=[],
        help="Relationship type to skip in focused mode. Can be used more than once.",
    )
    args = parser.parse_args()

    graph_path = Path(args.graph_json)
    output_path = Path(args.output)
    graph = json.loads(graph_path.read_text(encoding="utf-8"))
    try:
        if args.application_name or args.application_id:
            viewer_graph = focus_application_graph(
                graph,
                application_name=args.application_name,
                application_id=args.application_id,
                depth=args.focus_depth,
                max_nodes=args.max_nodes,
                max_edges=args.max_edges,
                exclude_edge_types=set(args.exclude_edge_type),
            )
        elif args.full:
            viewer_graph = with_metadata(graph, sampled=False)
        else:
            viewer_graph = sample_graph(graph, max_nodes=args.max_nodes, max_edges=args.max_edges)
    except ValueError as exc:
        parser.error(str(exc))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_html(viewer_graph), encoding="utf-8")
    print(f"Wrote graph viewer to {output_path}")
    metadata = viewer_graph.get("metadata", {})
    if metadata.get("focused"):
        print(
            "Rendered focused graph: "
            f"{len(viewer_graph['nodes'])}/{metadata['original_node_count']} nodes, "
            f"{len(viewer_graph['edges'])}/{metadata['original_edge_count']} edges, "
            f"{metadata['focus_root_count']} matching application(s), "
            f"depth {metadata['focus_depth']}"
        )
    elif metadata.get("sampled"):
        print(
            "Rendered sample: "
            f"{len(viewer_graph['nodes'])}/{metadata['original_node_count']} nodes, "
            f"{len(viewer_graph['edges'])}/{metadata['original_edge_count']} edges"
        )


EDGE_PRIORITY = {
    "HAS_OBSOLESCENCE_RECORD": 0,
    "ON_HOST": 1,
    "REFERENCES_TECHNOLOGY": 1,
    "HAS_CRITICALITY": 2,
    "IN_ENVIRONMENT": 2,
    "LOCATED_IN_COUNTRY": 2,
    "DEPLOYED_ON": 3,
    "USES_TECHNOLOGY": 3,
    "HAS_TECHNOLOGY": 3,
    "EXPOSES_DAP": 4,
    "HAS_DAP_BINDING": 4,
    "TARGETS_DAP": 4,
    "HAS_APPLICATION_MANAGER": 5,
    "HAS_APM_SPOC": 5,
    "HAS_DOMAIN_MANAGER": 5,
    "HAS_PRODUCTION_DOMAIN_MANAGER": 5,
    "HAS_PRODUCTION_MANAGER": 5,
    "HAS_APPLICATION": 6,
    "HAS_SUBCLUSTER": 6,
    "RELATED_TO": 50,
}


def focus_application_graph(
    graph: dict,
    *,
    application_name: str | None,
    application_id: str | None,
    depth: int,
    max_nodes: int,
    max_edges: int,
    exclude_edge_types: set[str] | None = None,
) -> dict:
    if depth < 0:
        raise ValueError("--focus-depth must be 0 or greater")
    if max_nodes < 1:
        raise ValueError("--max-nodes must be at least 1 in focused mode")
    if max_edges < 0:
        raise ValueError("--max-edges must be 0 or greater in focused mode")

    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])
    nodes_by_key = {node["key"]: node for node in nodes}
    excluded = exclude_edge_types or set()
    root_nodes = find_application_nodes(nodes, application_name=application_name, application_id=application_id)
    root_nodes = root_nodes[:max_nodes]
    if not root_nodes:
        selector = application_id or application_name or ""
        raise ValueError(f"No Application node matched {selector!r}")

    adjacency: dict[str, list[int]] = {}
    for index, edge in enumerate(edges):
        if edge.get("type") in excluded:
            continue
        adjacency.setdefault(edge["start_key"], []).append(index)
        adjacency.setdefault(edge["end_key"], []).append(index)

    selected_node_keys = {node["key"] for node in root_nodes}
    selected_edge_indexes: set[int] = set()
    frontier = set(selected_node_keys)
    hit_node_limit = False
    hit_edge_limit = False

    for _ in range(depth):
        if not frontier or len(selected_edge_indexes) >= max_edges:
            break
        next_frontier: set[str] = set()
        candidate_edge_indexes = sorted(
            {edge_index for node_key in frontier for edge_index in adjacency.get(node_key, [])},
            key=lambda index: edge_sort_key(edges[index]),
        )
        for edge_index in candidate_edge_indexes:
            if len(selected_edge_indexes) >= max_edges:
                hit_edge_limit = True
                break
            if edge_index in selected_edge_indexes:
                continue
            edge = edges[edge_index]
            start_key = edge["start_key"]
            end_key = edge["end_key"]
            other_keys = [key for key in (start_key, end_key) if key not in selected_node_keys]
            if len(selected_node_keys) + len(other_keys) > max_nodes:
                hit_node_limit = True
                continue
            for key in other_keys:
                if key in nodes_by_key:
                    selected_node_keys.add(key)
                    next_frontier.add(key)
            if start_key in selected_node_keys and end_key in selected_node_keys:
                selected_edge_indexes.add(edge_index)
        frontier = next_frontier

    for edge_index, edge in sorted(enumerate(edges), key=lambda item: edge_sort_key(item[1])):
        if len(selected_edge_indexes) >= max_edges:
            hit_edge_limit = True
            break
        if edge.get("type") in excluded:
            continue
        if edge["start_key"] in selected_node_keys and edge["end_key"] in selected_node_keys:
            selected_edge_indexes.add(edge_index)

    selected_nodes = [node for node in nodes if node["key"] in selected_node_keys]
    selected_edges = [edge for index, edge in enumerate(edges) if index in selected_edge_indexes]
    metadata = {
        "sampled": len(selected_nodes) < len(nodes) or len(selected_edges) < len(edges),
        "focused": True,
        "focus_application_name": application_name,
        "focus_application_id": application_id,
        "focus_depth": depth,
        "focus_root_count": len(root_nodes),
        "focus_roots": [node["key"] for node in root_nodes],
        "excluded_edge_types": sorted(excluded),
        "original_node_count": len(nodes),
        "original_edge_count": len(edges),
        "rendered_node_count": len(selected_nodes),
        "rendered_edge_count": len(selected_edges),
        "max_nodes": max_nodes,
        "max_edges": max_edges,
        "hit_node_limit": hit_node_limit,
        "hit_edge_limit": hit_edge_limit,
    }
    return {
        "nodes": selected_nodes,
        "edges": selected_edges,
        "warnings": graph.get("warnings", []),
        "metadata": metadata,
    }


def find_application_nodes(
    nodes: list[dict],
    *,
    application_name: str | None,
    application_id: str | None,
) -> list[dict]:
    applications = [node for node in nodes if node.get("label") == "Application"]
    normalized_id = normalize_search(application_id) if application_id else ""
    normalized_name = normalize_search(application_name) if application_name else ""

    matches = []
    for node in applications:
        props = node.get("properties", {})
        id_fields = [node.get("identity", ""), props.get("id", ""), node.get("key", "")]
        name_fields = [props.get("name", ""), node.get("identity", ""), props.get("id", ""), node.get("key", "")]
        id_match = normalized_id and any(normalize_search(value) == normalized_id for value in id_fields)
        name_match = normalized_name and any(normalized_name in normalize_search(value) for value in name_fields)
        if id_match or name_match:
            exact_name = normalized_name and normalize_search(props.get("name", "")) == normalized_name
            matches.append((not id_match, not exact_name, node.get("key", ""), node))

    return [item[3] for item in sorted(matches)]


def normalize_search(value: object) -> str:
    return " ".join(str(value).casefold().split())


def edge_sort_key(edge: dict) -> tuple[int, str, str, str]:
    edge_type = edge.get("type", "")
    return (
        EDGE_PRIORITY.get(edge_type, 20),
        edge_type,
        edge.get("start_key", ""),
        edge.get("end_key", ""),
    )


def sample_graph(graph: dict, *, max_nodes: int, max_edges: int) -> dict:
    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])
    if len(nodes) <= max_nodes and len(edges) <= max_edges:
        return with_metadata(graph, sampled=False)

    nodes_by_key = {node["key"]: node for node in nodes}
    degree: dict[str, int] = {node["key"]: 0 for node in nodes}
    for edge in edges:
        degree[edge["start_key"]] = degree.get(edge["start_key"], 0) + 1
        degree[edge["end_key"]] = degree.get(edge["end_key"], 0) + 1

    selected_node_keys: set[str] = set()
    selected_edge_indexes: set[int] = set()

    def add_node(key: str) -> bool:
        if key in selected_node_keys:
            return True
        if key not in nodes_by_key:
            return False
        if len(selected_node_keys) >= max_nodes:
            return False
        selected_node_keys.add(key)
        return True

    def force_node(key: str) -> None:
        if key in nodes_by_key:
            selected_node_keys.add(key)

    def add_edge(index: int, *, force: bool = False) -> bool:
        edge = edges[index]
        if force:
            force_node(edge["start_key"])
            force_node(edge["end_key"])
            selected_edge_indexes.add(index)
            return True
        missing = [
            key
            for key in (edge["start_key"], edge["end_key"])
            if key not in selected_node_keys
        ]
        if len(selected_node_keys) + len(missing) > max_nodes:
            return False
        for key in missing:
            add_node(key)
        selected_edge_indexes.add(index)
        return True

    labels = sorted({node.get("label", "") for node in nodes})
    for label in labels:
        candidates = [node for node in nodes if node.get("label") == label]
        if not candidates:
            continue
        best = max(candidates, key=lambda node: (degree.get(node["key"], 0), node["key"]))
        add_node(best["key"])

    edge_types = sorted({edge.get("type", "") for edge in edges})
    for edge_type in edge_types:
        candidates = [
            (index, edge)
            for index, edge in enumerate(edges)
            if edge.get("type") == edge_type
            and edge.get("start_key") in nodes_by_key
            and edge.get("end_key") in nodes_by_key
        ]
        if not candidates:
            continue
        best_index, _ = min(
            candidates,
            key=lambda item: (
                int(item[1]["start_key"] not in selected_node_keys)
                + int(item[1]["end_key"] not in selected_node_keys),
                item[1]["start_key"],
                item[1]["end_key"],
            ),
        )
        add_edge(best_index, force=True)

    adjacency: dict[str, list[int]] = {}
    for index, edge in enumerate(edges):
        adjacency.setdefault(edge["start_key"], []).append(index)
        adjacency.setdefault(edge["end_key"], []).append(index)

    queue = sorted(selected_node_keys, key=lambda key: (-degree.get(key, 0), key))
    seen_queue: set[str] = set(queue)
    while queue and len(selected_node_keys) < max_nodes and len(selected_edge_indexes) < max_edges:
        key = queue.pop(0)
        for edge_index in sorted(adjacency.get(key, []), key=lambda idx: edges[idx].get("type", "")):
            if len(selected_edge_indexes) >= max_edges:
                break
            edge = edges[edge_index]
            other_key = edge["end_key"] if edge["start_key"] == key else edge["start_key"]
            before_nodes = len(selected_node_keys)
            if not add_edge(edge_index):
                continue
            if len(selected_node_keys) > before_nodes and other_key not in seen_queue:
                queue.append(other_key)
                seen_queue.add(other_key)

    for index, edge in enumerate(edges):
        if len(selected_edge_indexes) >= max_edges:
            break
        if edge["start_key"] in selected_node_keys and edge["end_key"] in selected_node_keys:
            selected_edge_indexes.add(index)

    selected_nodes = [node for node in nodes if node["key"] in selected_node_keys]
    selected_edges = [edge for index, edge in enumerate(edges) if index in selected_edge_indexes]
    return {
        "nodes": selected_nodes,
        "edges": selected_edges,
        "warnings": graph.get("warnings", []),
        "metadata": {
            "sampled": True,
            "original_node_count": len(nodes),
            "original_edge_count": len(edges),
            "rendered_node_count": len(selected_nodes),
            "rendered_edge_count": len(selected_edges),
            "max_nodes": max_nodes,
            "max_edges": max_edges,
        },
    }


def with_metadata(graph: dict, *, sampled: bool) -> dict:
    clone = dict(graph)
    clone["metadata"] = {
        **clone.get("metadata", {}),
        "sampled": sampled,
        "original_node_count": len(clone.get("nodes", [])),
        "original_edge_count": len(clone.get("edges", [])),
        "rendered_node_count": len(clone.get("nodes", [])),
        "rendered_edge_count": len(clone.get("edges", [])),
    }
    return clone


def render_html(graph: dict) -> str:
    graph_json = json.dumps(graph, ensure_ascii=True, separators=(",", ":"))
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Infrastructure Topology Graph</title>
  <style>
    :root {{
      --bg: #f7f8fa;
      --panel: #ffffff;
      --ink: #16202a;
      --muted: #5d6975;
      --line: #d7dce2;
      --accent: #0f766e;
      --selected: #c2410c;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      min-height: 100vh;
      color: var(--ink);
      background: var(--bg);
      font: 14px/1.45 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    .app {{
      display: grid;
      grid-template-columns: minmax(0, 1fr) 360px;
      grid-template-rows: auto minmax(0, 1fr);
      min-height: 100vh;
    }}
    header {{
      grid-column: 1 / -1;
      display: flex;
      align-items: center;
      gap: 16px;
      padding: 12px 16px;
      border-bottom: 1px solid var(--line);
      background: var(--panel);
    }}
    h1 {{
      margin: 0;
      font-size: 18px;
      font-weight: 650;
      letter-spacing: 0;
    }}
    .counts {{
      display: flex;
      gap: 12px;
      color: var(--muted);
      white-space: nowrap;
    }}
    .controls {{
      display: flex;
      align-items: center;
      gap: 8px;
      margin-left: auto;
    }}
    input, select, button {{
      height: 34px;
      border: 1px solid var(--line);
      border-radius: 6px;
      background: #fff;
      color: var(--ink);
      padding: 0 10px;
      font: inherit;
    }}
    input {{ width: 260px; }}
    button {{
      cursor: pointer;
      background: #eef6f5;
      border-color: #b9d9d5;
      color: #0f5f58;
      font-weight: 600;
    }}
    main {{
      min-width: 0;
      min-height: 0;
      position: relative;
    }}
    svg {{
      width: 100%;
      height: calc(100vh - 59px);
      display: block;
      background: #fbfcfd;
    }}
    aside {{
      min-height: 0;
      overflow: auto;
      border-left: 1px solid var(--line);
      background: var(--panel);
      padding: 16px;
    }}
    .legend {{
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 8px;
      margin-bottom: 16px;
    }}
    .legend-item {{
      display: flex;
      align-items: center;
      gap: 8px;
      color: var(--muted);
      min-width: 0;
    }}
    .swatch {{
      width: 12px;
      height: 12px;
      border-radius: 50%;
      flex: 0 0 auto;
    }}
    .node circle {{
      stroke: #fff;
      stroke-width: 2;
      cursor: pointer;
    }}
    .node.selected circle {{
      stroke: var(--selected);
      stroke-width: 4;
    }}
    .node text {{
      pointer-events: none;
      font-size: 11px;
      paint-order: stroke;
      stroke: #fff;
      stroke-width: 3px;
      fill: #16202a;
    }}
    .edge {{
      stroke: #8f9aa7;
      stroke-opacity: 0.58;
      stroke-width: 1.5;
      marker-end: url(#arrow);
    }}
    .edge.highlight {{
      stroke: var(--selected);
      stroke-opacity: 0.9;
      stroke-width: 2.5;
    }}
    .edge-label {{
      pointer-events: none;
      font-size: 9px;
      font-weight: 650;
      letter-spacing: 0;
      fill: #334155;
      paint-order: stroke;
      stroke: #fbfcfd;
      stroke-width: 4px;
      stroke-linejoin: round;
    }}
    .edge-label.highlight {{
      fill: var(--selected);
    }}
    .details h2 {{
      margin: 0 0 4px;
      font-size: 17px;
      letter-spacing: 0;
    }}
    .details .sub {{
      color: var(--muted);
      margin-bottom: 14px;
    }}
    .property {{
      display: grid;
      grid-template-columns: 120px minmax(0, 1fr);
      gap: 10px;
      padding: 7px 0;
      border-top: 1px solid #edf0f3;
    }}
    .property b {{
      color: var(--muted);
      font-weight: 600;
      overflow-wrap: anywhere;
    }}
    .property span {{
      overflow-wrap: anywhere;
    }}
    .empty {{
      color: var(--muted);
    }}
    @media (max-width: 900px) {{
      .app {{
        grid-template-columns: 1fr;
        grid-template-rows: auto minmax(420px, 1fr) auto;
      }}
      aside {{ border-left: 0; border-top: 1px solid var(--line); }}
      header {{ align-items: stretch; flex-direction: column; }}
      .controls {{ margin-left: 0; flex-wrap: wrap; }}
      input {{ width: min(100%, 320px); }}
      svg {{ height: 60vh; min-height: 420px; }}
    }}
  </style>
</head>
<body>
  <div class="app">
    <header>
      <h1>Infrastructure Topology Graph</h1>
      <div class="counts" id="counts"></div>
      <div class="controls">
        <input id="search" type="search" placeholder="Search id, name, host, technology">
        <select id="labelFilter"></select>
        <button id="reset">Reset</button>
      </div>
    </header>
    <main>
      <svg id="graph" role="img" aria-label="Topology graph"></svg>
    </main>
    <aside>
      <div class="legend" id="legend"></div>
      <section class="details" id="details">
        <h2>Select a node</h2>
        <div class="sub">Click any node to inspect all source properties.</div>
      </section>
    </aside>
  </div>
  <script>
    const graph = {graph_json};
    const palette = {{
      Application: "#2563eb",
      ApplicationDap: "#0891b2",
      Cluster: "#16a34a",
      Contact: "#be123c",
      Criticality: "#b45309",
      Dap: "#7c3aed",
      Environment: "#0f766e",
      Host: "#ea580c",
      LocationCountry: "#0369a1",
      ObsolescenceRecord: "#dc2626",
      Subcluster: "#65a30d",
      Technology: "#9333ea"
    }};

    const svg = document.getElementById("graph");
    const countsEl = document.getElementById("counts");
    const searchEl = document.getElementById("search");
    const labelFilterEl = document.getElementById("labelFilter");
    const resetEl = document.getElementById("reset");
    const legendEl = document.getElementById("legend");
    const detailsEl = document.getElementById("details");

    let selectedKey = null;
    let renderedNodes = [];
    let renderedEdges = [];

    const nodesByKey = new Map(graph.nodes.map(node => [node.key, node]));
    const labels = [...new Set(graph.nodes.map(node => node.label))].sort();
    labelFilterEl.innerHTML = '<option value="">All labels</option>' + labels.map(label => (
      `<option value="${{escapeHtml(label)}}">${{escapeHtml(label)}}</option>`
    )).join("");

    legendEl.innerHTML = labels.map(label => (
      `<div class="legend-item"><span class="swatch" style="background:${{palette[label] || "#64748b"}}"></span><span>${{escapeHtml(label)}}</span></div>`
    )).join("");

    const metadata = graph.metadata || {{}};
    if (metadata.focused) {{
      const limitText = metadata.hit_node_limit || metadata.hit_edge_limit ? " - limit reached" : "";
      countsEl.textContent = `${{graph.nodes.length}}/${{metadata.original_node_count}} nodes - ${{graph.edges.length}}/${{metadata.original_edge_count}} edges focused on ${{metadata.focus_root_count}} app match(es), depth ${{metadata.focus_depth}}${{limitText}}`;
    }} else if (metadata.sampled) {{
      countsEl.textContent = `${{graph.nodes.length}}/${{metadata.original_node_count}} nodes - ${{graph.edges.length}}/${{metadata.original_edge_count}} edges sampled`;
    }} else {{
      countsEl.textContent = `${{graph.nodes.length}} nodes / ${{graph.edges.length}} edges`;
    }}

    function nodeText(node) {{
      const props = node.properties || {{}};
      return [
        node.key,
        node.label,
        node.identity,
        props.id,
        props.name,
        props.host,
        props.dap_name,
        props.retrieval_text
      ].filter(Boolean).join(" ").toLowerCase();
    }}

    function nodeName(node) {{
      const props = node.properties || {{}};
      return props.name || props.host || props.dap_name || props.id || node.identity;
    }}

    function applyFilters() {{
      const query = searchEl.value.trim().toLowerCase();
      const label = labelFilterEl.value;
      const visibleKeys = new Set();
      renderedNodes = graph.nodes.filter(node => {{
        const matchesLabel = !label || node.label === label;
        const matchesQuery = !query || nodeText(node).includes(query);
        if (matchesLabel && matchesQuery) visibleKeys.add(node.key);
        return matchesLabel && matchesQuery;
      }});
      renderedEdges = graph.edges.filter(edge => visibleKeys.has(edge.start_key) && visibleKeys.has(edge.end_key));
      layoutAndRender();
    }}

    function layoutAndRender() {{
      const rect = svg.getBoundingClientRect();
      const width = Math.max(640, rect.width || 900);
      const height = Math.max(420, rect.height || 700);
      svg.setAttribute("viewBox", `0 0 ${{width}} ${{height}}`);
      svg.innerHTML = `
        <defs>
          <marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto" markerUnits="strokeWidth">
            <path d="M0,0 L0,6 L7,3 z" fill="#8f9aa7"></path>
          </marker>
        </defs>
      `;

      const nodes = renderedNodes.map((node, index) => {{
        const angle = (index / Math.max(1, renderedNodes.length)) * Math.PI * 2;
        return {{
          ...node,
          x: width / 2 + Math.cos(angle) * width * 0.28,
          y: height / 2 + Math.sin(angle) * height * 0.28,
          vx: 0,
          vy: 0
        }};
      }});
      const byKey = new Map(nodes.map(node => [node.key, node]));
      const edges = renderedEdges
        .map(edge => ({{...edge, source: byKey.get(edge.start_key), target: byKey.get(edge.end_key)}}))
        .filter(edge => edge.source && edge.target);

      for (let i = 0; i < 180; i += 1) {{
        for (const edge of edges) {{
          const dx = edge.target.x - edge.source.x;
          const dy = edge.target.y - edge.source.y;
          const dist = Math.sqrt(dx * dx + dy * dy) || 1;
          const force = (dist - 110) * 0.004;
          const fx = (dx / dist) * force;
          const fy = (dy / dist) * force;
          edge.source.vx += fx;
          edge.source.vy += fy;
          edge.target.vx -= fx;
          edge.target.vy -= fy;
        }}
        for (let a = 0; a < nodes.length; a += 1) {{
          for (let b = a + 1; b < nodes.length; b += 1) {{
            const left = nodes[a];
            const right = nodes[b];
            const dx = right.x - left.x;
            const dy = right.y - left.y;
            const distSq = Math.max(100, dx * dx + dy * dy);
            const dist = Math.sqrt(distSq);
            const force = 650 / distSq;
            const fx = (dx / dist) * force;
            const fy = (dy / dist) * force;
            left.vx -= fx;
            left.vy -= fy;
            right.vx += fx;
            right.vy += fy;
          }}
        }}
        for (const node of nodes) {{
          node.vx += (width / 2 - node.x) * 0.002;
          node.vy += (height / 2 - node.y) * 0.002;
          node.x = Math.min(width - 80, Math.max(80, node.x + node.vx));
          node.y = Math.min(height - 50, Math.max(50, node.y + node.vy));
          node.vx *= 0.84;
          node.vy *= 0.84;
        }}
      }}

      const edgeLayer = document.createElementNS("http://www.w3.org/2000/svg", "g");
      const labelLayer = document.createElementNS("http://www.w3.org/2000/svg", "g");
      const nodeLayer = document.createElementNS("http://www.w3.org/2000/svg", "g");
      svg.appendChild(edgeLayer);
      svg.appendChild(labelLayer);
      svg.appendChild(nodeLayer);

      for (const edge of edges) {{
        const highlighted = edgeTouchesSelection(edge);
        const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
        line.setAttribute("class", highlighted ? "edge highlight" : "edge");
        line.setAttribute("x1", edge.source.x);
        line.setAttribute("y1", edge.source.y);
        line.setAttribute("x2", edge.target.x);
        line.setAttribute("y2", edge.target.y);
        line.appendChild(svgTitle(`${{edge.type}}\\n${{edge.start_key}} -> ${{edge.end_key}}`));
        edgeLayer.appendChild(line);

        const label = document.createElementNS("http://www.w3.org/2000/svg", "text");
        label.setAttribute("class", highlighted ? "edge-label highlight" : "edge-label");
        label.setAttribute("x", (edge.source.x + edge.target.x) / 2);
        label.setAttribute("y", (edge.source.y + edge.target.y) / 2 - 4);
        label.setAttribute("text-anchor", "middle");
        label.textContent = edge.type;
        labelLayer.appendChild(label);
      }}

      for (const node of nodes) {{
        const group = document.createElementNS("http://www.w3.org/2000/svg", "g");
        group.setAttribute("class", node.key === selectedKey ? "node selected" : "node");
        group.setAttribute("transform", `translate(${{node.x}},${{node.y}})`);
        group.addEventListener("click", () => {{
          selectedKey = node.key;
          showDetails(node);
          layoutAndRender();
        }});

        const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
        circle.setAttribute("r", nodeRadius(node.label));
        circle.setAttribute("fill", palette[node.label] || "#64748b");
        group.appendChild(circle);
        group.appendChild(svgTitle(`${{node.label}}\\n${{nodeName(node)}}\\n${{node.key}}`));

        const text = document.createElementNS("http://www.w3.org/2000/svg", "text");
        text.setAttribute("x", nodeRadius(node.label) + 6);
        text.setAttribute("y", 4);
        text.textContent = truncate(nodeName(node), 28);
        group.appendChild(text);
        nodeLayer.appendChild(group);
      }}

      if (!nodes.length) {{
        const empty = document.createElementNS("http://www.w3.org/2000/svg", "text");
        empty.setAttribute("x", width / 2);
        empty.setAttribute("y", height / 2);
        empty.setAttribute("text-anchor", "middle");
        empty.setAttribute("fill", "#5d6975");
        empty.textContent = "No nodes match the current filters";
        svg.appendChild(empty);
      }}
    }}

    function edgeTouchesSelection(edge) {{
      return selectedKey && (edge.start_key === selectedKey || edge.end_key === selectedKey);
    }}

    function nodeRadius(label) {{
      if (label === "Application") return 13;
      if (label === "Cluster") return 15;
      if (label === "Host") return 11;
      return 10;
    }}

    function svgTitle(text) {{
      const title = document.createElementNS("http://www.w3.org/2000/svg", "title");
      title.textContent = text;
      return title;
    }}

    function showDetails(node) {{
      const props = node.properties || {{}};
      const rows = Object.entries(props).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => {{
        const valueText = Array.isArray(value) ? value.join(", ") : String(value);
        return `<div class="property"><b>${{escapeHtml(key)}}</b><span>${{escapeHtml(valueText)}}</span></div>`;
      }}).join("");
      const connected = graph.edges.filter(edge => edge.start_key === node.key || edge.end_key === node.key);
      const edgeRows = connected.slice(0, 24).map(edge => {{
        const direction = edge.start_key === node.key ? "out" : "in";
        const otherKey = edge.start_key === node.key ? edge.end_key : edge.start_key;
        return `<div class="property"><b>${{escapeHtml(direction)}}</b><span>${{escapeHtml(edge.type)}} -> ${{escapeHtml(otherKey)}}</span></div>`;
      }}).join("");
      detailsEl.innerHTML = `
        <h2>${{escapeHtml(nodeName(node))}}</h2>
        <div class="sub">${{escapeHtml(node.label)}} / ${{escapeHtml(node.identity)}}</div>
        <h3>Properties</h3>
        ${{rows || '<div class="empty">No properties</div>'}}
        <h3>Relationships</h3>
        ${{edgeRows || '<div class="empty">No relationships</div>'}}
      `;
    }}

    function truncate(text, limit) {{
      return text.length <= limit ? text : text.slice(0, limit - 1) + "...";
    }}

    function escapeHtml(value) {{
      return String(value).replace(/[&<>"']/g, char => ({{
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        "\\"": "&quot;",
        "'": "&#39;"
      }}[char]));
    }}

    searchEl.addEventListener("input", applyFilters);
    labelFilterEl.addEventListener("change", applyFilters);
    resetEl.addEventListener("click", () => {{
      searchEl.value = "";
      labelFilterEl.value = "";
      selectedKey = null;
      detailsEl.innerHTML = '<h2>Select a node</h2><div class="sub">Click any node to inspect all source properties.</div>';
      applyFilters();
    }});
    window.addEventListener("resize", () => layoutAndRender());

    applyFilters();
  </script>
</body>
</html>
"""


if __name__ == "__main__":
    main()
