#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Render a self-contained HTML topology graph viewer.")
    parser.add_argument("--graph-json", default="build/topology_graph.json", help="Graph JSON generated by export_graph.py.")
    parser.add_argument("--output", default="build/topology_viewer.html", help="Output HTML file.")
    args = parser.parse_args()

    graph_path = Path(args.graph_json)
    output_path = Path(args.output)
    graph = json.loads(graph_path.read_text(encoding="utf-8"))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_html(graph), encoding="utf-8")
    print(f"Wrote graph viewer to {output_path}")


def render_html(graph: dict) -> str:
    graph_json = json.dumps(graph, ensure_ascii=True, separators=(",", ":"))
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Infrastructure Topology Graph</title>
  <style>
    :root {{
      --bg: #f7f8fa;
      --panel: #ffffff;
      --ink: #16202a;
      --muted: #5d6975;
      --line: #d7dce2;
      --accent: #0f766e;
      --selected: #c2410c;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      min-height: 100vh;
      color: var(--ink);
      background: var(--bg);
      font: 14px/1.45 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    .app {{
      display: grid;
      grid-template-columns: minmax(0, 1fr) 360px;
      grid-template-rows: auto minmax(0, 1fr);
      min-height: 100vh;
    }}
    header {{
      grid-column: 1 / -1;
      display: flex;
      align-items: center;
      gap: 16px;
      padding: 12px 16px;
      border-bottom: 1px solid var(--line);
      background: var(--panel);
    }}
    h1 {{
      margin: 0;
      font-size: 18px;
      font-weight: 650;
      letter-spacing: 0;
    }}
    .counts {{
      display: flex;
      gap: 12px;
      color: var(--muted);
      white-space: nowrap;
    }}
    .controls {{
      display: flex;
      align-items: center;
      gap: 8px;
      margin-left: auto;
    }}
    input, select, button {{
      height: 34px;
      border: 1px solid var(--line);
      border-radius: 6px;
      background: #fff;
      color: var(--ink);
      padding: 0 10px;
      font: inherit;
    }}
    input {{ width: 260px; }}
    button {{
      cursor: pointer;
      background: #eef6f5;
      border-color: #b9d9d5;
      color: #0f5f58;
      font-weight: 600;
    }}
    main {{
      min-width: 0;
      min-height: 0;
      position: relative;
    }}
    svg {{
      width: 100%;
      height: calc(100vh - 59px);
      display: block;
      background: #fbfcfd;
    }}
    aside {{
      min-height: 0;
      overflow: auto;
      border-left: 1px solid var(--line);
      background: var(--panel);
      padding: 16px;
    }}
    .legend {{
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 8px;
      margin-bottom: 16px;
    }}
    .legend-item {{
      display: flex;
      align-items: center;
      gap: 8px;
      color: var(--muted);
      min-width: 0;
    }}
    .swatch {{
      width: 12px;
      height: 12px;
      border-radius: 50%;
      flex: 0 0 auto;
    }}
    .node circle {{
      stroke: #fff;
      stroke-width: 2;
      cursor: pointer;
    }}
    .node.selected circle {{
      stroke: var(--selected);
      stroke-width: 4;
    }}
    .node text {{
      pointer-events: none;
      font-size: 11px;
      paint-order: stroke;
      stroke: #fff;
      stroke-width: 3px;
      fill: #16202a;
    }}
    .edge {{
      stroke: #8f9aa7;
      stroke-opacity: 0.58;
      stroke-width: 1.5;
      marker-end: url(#arrow);
    }}
    .edge.highlight {{
      stroke: var(--selected);
      stroke-opacity: 0.9;
      stroke-width: 2.5;
    }}
    .details h2 {{
      margin: 0 0 4px;
      font-size: 17px;
      letter-spacing: 0;
    }}
    .details .sub {{
      color: var(--muted);
      margin-bottom: 14px;
    }}
    .property {{
      display: grid;
      grid-template-columns: 120px minmax(0, 1fr);
      gap: 10px;
      padding: 7px 0;
      border-top: 1px solid #edf0f3;
    }}
    .property b {{
      color: var(--muted);
      font-weight: 600;
      overflow-wrap: anywhere;
    }}
    .property span {{
      overflow-wrap: anywhere;
    }}
    .empty {{
      color: var(--muted);
    }}
    @media (max-width: 900px) {{
      .app {{
        grid-template-columns: 1fr;
        grid-template-rows: auto minmax(420px, 1fr) auto;
      }}
      aside {{ border-left: 0; border-top: 1px solid var(--line); }}
      header {{ align-items: stretch; flex-direction: column; }}
      .controls {{ margin-left: 0; flex-wrap: wrap; }}
      input {{ width: min(100%, 320px); }}
      svg {{ height: 60vh; min-height: 420px; }}
    }}
  </style>
</head>
<body>
  <div class="app">
    <header>
      <h1>Infrastructure Topology Graph</h1>
      <div class="counts" id="counts"></div>
      <div class="controls">
        <input id="search" type="search" placeholder="Search id, name, host, technology">
        <select id="labelFilter"></select>
        <button id="reset">Reset</button>
      </div>
    </header>
    <main>
      <svg id="graph" role="img" aria-label="Topology graph"></svg>
    </main>
    <aside>
      <div class="legend" id="legend"></div>
      <section class="details" id="details">
        <h2>Select a node</h2>
        <div class="sub">Click any node to inspect all source properties.</div>
      </section>
    </aside>
  </div>
  <script>
    const graph = {graph_json};
    const palette = {{
      Application: "#2563eb",
      ApplicationDap: "#0891b2",
      Cluster: "#16a34a",
      Dap: "#7c3aed",
      Host: "#ea580c",
      ObsolescenceRecord: "#dc2626",
      Subcluster: "#65a30d",
      Technology: "#9333ea"
    }};

    const svg = document.getElementById("graph");
    const countsEl = document.getElementById("counts");
    const searchEl = document.getElementById("search");
    const labelFilterEl = document.getElementById("labelFilter");
    const resetEl = document.getElementById("reset");
    const legendEl = document.getElementById("legend");
    const detailsEl = document.getElementById("details");

    let selectedKey = null;
    let renderedNodes = [];
    let renderedEdges = [];

    const nodesByKey = new Map(graph.nodes.map(node => [node.key, node]));
    const labels = [...new Set(graph.nodes.map(node => node.label))].sort();
    labelFilterEl.innerHTML = '<option value="">All labels</option>' + labels.map(label => (
      `<option value="${{escapeHtml(label)}}">${{escapeHtml(label)}}</option>`
    )).join("");

    legendEl.innerHTML = labels.map(label => (
      `<div class="legend-item"><span class="swatch" style="background:${{palette[label] || "#64748b"}}"></span><span>${{escapeHtml(label)}}</span></div>`
    )).join("");

    countsEl.textContent = `${{graph.nodes.length}} nodes / ${{graph.edges.length}} edges`;

    function nodeText(node) {{
      const props = node.properties || {{}};
      return [
        node.key,
        node.label,
        node.identity,
        props.id,
        props.name,
        props.host,
        props.dap_name,
        props.retrieval_text
      ].filter(Boolean).join(" ").toLowerCase();
    }}

    function nodeName(node) {{
      const props = node.properties || {{}};
      return props.name || props.host || props.dap_name || props.id || node.identity;
    }}

    function applyFilters() {{
      const query = searchEl.value.trim().toLowerCase();
      const label = labelFilterEl.value;
      const visibleKeys = new Set();
      renderedNodes = graph.nodes.filter(node => {{
        const matchesLabel = !label || node.label === label;
        const matchesQuery = !query || nodeText(node).includes(query);
        if (matchesLabel && matchesQuery) visibleKeys.add(node.key);
        return matchesLabel && matchesQuery;
      }});
      renderedEdges = graph.edges.filter(edge => visibleKeys.has(edge.start_key) && visibleKeys.has(edge.end_key));
      layoutAndRender();
    }}

    function layoutAndRender() {{
      const rect = svg.getBoundingClientRect();
      const width = Math.max(640, rect.width || 900);
      const height = Math.max(420, rect.height || 700);
      svg.setAttribute("viewBox", `0 0 ${{width}} ${{height}}`);
      svg.innerHTML = `
        <defs>
          <marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto" markerUnits="strokeWidth">
            <path d="M0,0 L0,6 L7,3 z" fill="#8f9aa7"></path>
          </marker>
        </defs>
      `;

      const nodes = renderedNodes.map((node, index) => {{
        const angle = (index / Math.max(1, renderedNodes.length)) * Math.PI * 2;
        return {{
          ...node,
          x: width / 2 + Math.cos(angle) * width * 0.28,
          y: height / 2 + Math.sin(angle) * height * 0.28,
          vx: 0,
          vy: 0
        }};
      }});
      const byKey = new Map(nodes.map(node => [node.key, node]));
      const edges = renderedEdges
        .map(edge => ({{...edge, source: byKey.get(edge.start_key), target: byKey.get(edge.end_key)}}))
        .filter(edge => edge.source && edge.target);

      for (let i = 0; i < 180; i += 1) {{
        for (const edge of edges) {{
          const dx = edge.target.x - edge.source.x;
          const dy = edge.target.y - edge.source.y;
          const dist = Math.sqrt(dx * dx + dy * dy) || 1;
          const force = (dist - 110) * 0.004;
          const fx = (dx / dist) * force;
          const fy = (dy / dist) * force;
          edge.source.vx += fx;
          edge.source.vy += fy;
          edge.target.vx -= fx;
          edge.target.vy -= fy;
        }}
        for (let a = 0; a < nodes.length; a += 1) {{
          for (let b = a + 1; b < nodes.length; b += 1) {{
            const left = nodes[a];
            const right = nodes[b];
            const dx = right.x - left.x;
            const dy = right.y - left.y;
            const distSq = Math.max(100, dx * dx + dy * dy);
            const dist = Math.sqrt(distSq);
            const force = 650 / distSq;
            const fx = (dx / dist) * force;
            const fy = (dy / dist) * force;
            left.vx -= fx;
            left.vy -= fy;
            right.vx += fx;
            right.vy += fy;
          }}
        }}
        for (const node of nodes) {{
          node.vx += (width / 2 - node.x) * 0.002;
          node.vy += (height / 2 - node.y) * 0.002;
          node.x = Math.min(width - 80, Math.max(80, node.x + node.vx));
          node.y = Math.min(height - 50, Math.max(50, node.y + node.vy));
          node.vx *= 0.84;
          node.vy *= 0.84;
        }}
      }}

      const edgeLayer = document.createElementNS("http://www.w3.org/2000/svg", "g");
      const nodeLayer = document.createElementNS("http://www.w3.org/2000/svg", "g");
      svg.appendChild(edgeLayer);
      svg.appendChild(nodeLayer);

      for (const edge of edges) {{
        const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
        line.setAttribute("class", edgeTouchesSelection(edge) ? "edge highlight" : "edge");
        line.setAttribute("x1", edge.source.x);
        line.setAttribute("y1", edge.source.y);
        line.setAttribute("x2", edge.target.x);
        line.setAttribute("y2", edge.target.y);
        line.appendChild(svgTitle(`${{edge.type}}\\n${{edge.start_key}} -> ${{edge.end_key}}`));
        edgeLayer.appendChild(line);
      }}

      for (const node of nodes) {{
        const group = document.createElementNS("http://www.w3.org/2000/svg", "g");
        group.setAttribute("class", node.key === selectedKey ? "node selected" : "node");
        group.setAttribute("transform", `translate(${{node.x}},${{node.y}})`);
        group.addEventListener("click", () => {{
          selectedKey = node.key;
          showDetails(node);
          layoutAndRender();
        }});

        const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
        circle.setAttribute("r", nodeRadius(node.label));
        circle.setAttribute("fill", palette[node.label] || "#64748b");
        group.appendChild(circle);
        group.appendChild(svgTitle(`${{node.label}}\\n${{nodeName(node)}}\\n${{node.key}}`));

        const text = document.createElementNS("http://www.w3.org/2000/svg", "text");
        text.setAttribute("x", nodeRadius(node.label) + 6);
        text.setAttribute("y", 4);
        text.textContent = truncate(nodeName(node), 28);
        group.appendChild(text);
        nodeLayer.appendChild(group);
      }}

      if (!nodes.length) {{
        const empty = document.createElementNS("http://www.w3.org/2000/svg", "text");
        empty.setAttribute("x", width / 2);
        empty.setAttribute("y", height / 2);
        empty.setAttribute("text-anchor", "middle");
        empty.setAttribute("fill", "#5d6975");
        empty.textContent = "No nodes match the current filters";
        svg.appendChild(empty);
      }}
    }}

    function edgeTouchesSelection(edge) {{
      return selectedKey && (edge.start_key === selectedKey || edge.end_key === selectedKey);
    }}

    function nodeRadius(label) {{
      if (label === "Application") return 13;
      if (label === "Cluster") return 15;
      if (label === "Host") return 11;
      return 10;
    }}

    function svgTitle(text) {{
      const title = document.createElementNS("http://www.w3.org/2000/svg", "title");
      title.textContent = text;
      return title;
    }}

    function showDetails(node) {{
      const props = node.properties || {{}};
      const rows = Object.entries(props).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => {{
        const valueText = Array.isArray(value) ? value.join(", ") : String(value);
        return `<div class="property"><b>${{escapeHtml(key)}}</b><span>${{escapeHtml(valueText)}}</span></div>`;
      }}).join("");
      const connected = graph.edges.filter(edge => edge.start_key === node.key || edge.end_key === node.key);
      const edgeRows = connected.slice(0, 24).map(edge => {{
        const direction = edge.start_key === node.key ? "out" : "in";
        const otherKey = edge.start_key === node.key ? edge.end_key : edge.start_key;
        return `<div class="property"><b>${{escapeHtml(direction)}}</b><span>${{escapeHtml(edge.type)}} -> ${{escapeHtml(otherKey)}}</span></div>`;
      }}).join("");
      detailsEl.innerHTML = `
        <h2>${{escapeHtml(nodeName(node))}}</h2>
        <div class="sub">${{escapeHtml(node.label)}} / ${{escapeHtml(node.identity)}}</div>
        <h3>Properties</h3>
        ${{rows || '<div class="empty">No properties</div>'}}
        <h3>Relationships</h3>
        ${{edgeRows || '<div class="empty">No relationships</div>'}}
      `;
    }}

    function truncate(text, limit) {{
      return text.length <= limit ? text : text.slice(0, limit - 1) + "...";
    }}

    function escapeHtml(value) {{
      return String(value).replace(/[&<>"']/g, char => ({{
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        "\\"": "&quot;",
        "'": "&#39;"
      }}[char]));
    }}

    searchEl.addEventListener("input", applyFilters);
    labelFilterEl.addEventListener("change", applyFilters);
    resetEl.addEventListener("click", () => {{
      searchEl.value = "";
      labelFilterEl.value = "";
      selectedKey = null;
      detailsEl.innerHTML = '<h2>Select a node</h2><div class="sub">Click any node to inspect all source properties.</div>';
      applyFilters();
    }});
    window.addEventListener("resize", () => layoutAndRender());

    applyFilters();
  </script>
</body>
</html>
"""


if __name__ == "__main__":
    main()
